### ISSUE TITLE
[RFC] ZynAddSubFX buffer improvement, especially targeted for small system audio buffers

### ISSUE THREAD

**Issue by hselasky** [zynaddsubfx/zynaddsubfx#216]
Hi,

On some systems the buffer size is the same for all audio clients. This sometimes lead to problems, which are solved by letting ZynAddSubFX have a separate thread to generate audio, instead of doing the work synchronously to the audio subsystem.

--HPS

[0001-Let-InMgr-flush-return-a-boolean-indicating-if-all-M.txt](https://github.com/zynaddsubfx/zynaddsubfx/files/10060319/0001-Let-InMgr-flush-return-a-boolean-indicating-if-all-M.txt)
[0002-Implement-own-thread-for-rendering-samples-default-i.txt](https://github.com/zynaddsubfx/zynaddsubfx/files/10060320/0002-Implement-own-thread-for-rendering-samples-default-i.txt)
[0003-Automagically-enable-background-synth.txt](https://github.com/zynaddsubfx/zynaddsubfx/files/10060321/0003-Automagically-enable-background-synth.txt)

**Comment by fundamental** [comment]
I'm fairly confused as to why this should be needed. If an audio buffer size is too small for the system to generate realtime audio, then the system audio buffer should be increased, no?

**Comment by hselasky** [comment]
Hi,

Let me show you an example. There are some programs called Jamulus, Sonobus and HpsJAM which musicians use to play together on the internet. In this regard the JACK buffer size must be set to 32 or 64 bytes. If the ZynAddSubFX oscillator size is 1K samples, to get better audio, it frequently happens that ZynAddSubFX runs out of time to produce 1K samples in 32 samples time, and JACK starts complaining about underruns and late audio. For ALSA and OSS backends this is not a problem, and this new feature will never be triggered.

The problem is that the ZynAddSubFX load is not evenly distributed on each of the say, 32 sample intervals. In one of those intervals, ZynAddSubFX will do a lot of processing, and in the others, it will simply read from a buffer which is a NOP.

Did my explanation help your understanding?

--HPS

**Comment by fundamental** [comment]
So, generally I agree that note-on is the most expensive processing frames that zyn experiences, though producing 32 samples of data from a running note is not something I would declare to be a NOP. For jack it seems like adjusting the number of periods would be a good way of saying "process chunks of this size, but queue up X chunks" compared to the patchset which looks like it's going to run into issues because zyn would not be generating audio in the realtime context (i.e. the pull threading model of jack).

While non-ideal I could see how patching zyn would be the easiest way of resolving your issue if you're running intensive patches or have a system where realtime scheduling isn't ideal, but this patchset isn't something I would recommend to general users and it would negatively interact with any of the periodic work used to identify realtime safety faults via stoat ( @JohannesLorenz has been looking into that from time to time). Would a reasonable compromise be that this functionality is disabled by default in CMake and enabled in the code via a set of #ifdefs?

Ideally once the wavetable changeset is merged the cost of a note-on is considerably lower absolving the need for the proposed workaround.

**Comment by hselasky** [comment]
I have no problem introducing this behaviour as an ifdef, configurable by CMake. Technically the ifdef will go into patch 0003, around the enable clause. Is that OK by you?

**Comment by hselasky** [comment]
Jack only supports one period.

**Comment by fundamental** [comment]
I would say that most of the content of the 0002 patch would need to be ifdefed because for standard low latency operations with jack (or a similar audio backend) the synth (i.e. the sound generation portion) is assumed to run only in the jack callback thread.

**Comment by hselasky** [comment]
OK, no problem. I'll start working on it.

**Comment by hselasky** [comment]
Thank you for reviewing. Let me know if anything is broken and I will fix it.
