### ISSUE TITLE
How recreate new interface for this Synth?

### ISSUE THREAD

**Issue by rty65tt** [zynaddsubfx/zynaddsubfx#280]
Hi.
I success to compile for Win10 + Mingw64-ucrt, but using it via OSC is not convenient.
I want to make a audio plugin (vst3 and clap) version with a new user-friendly interface.
I have a concept for a new interface.
But I need advice on how this can be done.
How to leave only what is needed to open and play presets?
(Remove everything that is unnecessary for the audio plugin OSC, portaudio, jack, liblo, OSC, Alsa, etc.).

How to import into Juce or another framework for audio plugins in order to create an interface there (or maybe another solution, I’ve just only dealt with Juce so far)?
Is it even possible?

**Comment by fundamental** [comment]
Yeah, you're asking for too much here and are basically talking about a stripped down fork. It doesn't really make sense for most of the proposals. If you want to help move forward VST3/clap/other host support there was a pull request updating DPF which stalled out due to limitations in how many people were available to test on the windows platform at the time. Replacing the user interface would be a task out-of-scope for this issue tracker.

**Comment by rty65tt** [comment]
I'm trying to understand the structure of the code. It's very difficult. I was hoping for help from the author.

**Comment by fundamental** [comment]
We're around to answer specific questions, though avoiding things like our OSC interface and importing other audio frameworks would be a major departure from any of the existing code and the features it offers to help development.

**Comment by rty65tt** [comment]
May be avoiding things like your OSC interface and  importing other sound frameworks would bring this project back to life.
